### ISSUE TITLE
Cannot compile Verazt because of updates in inkwell

### ISSUE THREAD

**Issue by thanhtoantnt** [sbip-sg/inkwell#1]
Currently, I cannot compile `verazt` because of the mismatches between `inkwell` and `verazt`. I suspect it is because of the new updates in `inkwell` since they are newer. Otherwise, this slitting of `inkwell` should be in a separate branch to not causing compilation error when other people merge the `develop` branch in `verazt`.

**Comment by taquangtrung** [comment]
@thanhtoantnt: I just fixed the compilation issues. Yeah, next time, breaking changes should be done in a separate branch
